name: Deploy SIIT40 API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Lightsail via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Crear la carpeta de proyectos si no existe
            mkdir -p ~/proyectos
            cd ~/proyectos

            if [ ! -d "siit-api" ]; then
              git clone https://github.com/Luis3Fernando/SIIT40-Api.git
              cd siit-api
            else
              cd siit-api
              git pull origin main
            fi

            # Levantar los contenedores
            # Usamos 'docker compose' (V2) que instalamos manualmente
            ~/.docker/cli-plugins/docker-compose up -d --build